//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectv2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTbl
    {
        public int BId { get; set; }
        public int CustId { get; set; }
        public string CustName { get; set; }
        public int Amount { get; set; }
    }
}
